### ISSUE TITLE
Unable to cache gems at the default location

### ISSUE THREAD

**Issue by bhaskar-simpl** [CircleCI-Public/cimg-ruby#107]
The default location for installing gems `/usr/local/bundle` is not accessible by the circleci user.

**Comment by BytesGuy** [comment]
@bhaskar-simpl 

Hi, thanks for opening this issue.

If you intend to use gems with caching on CircleCI it is recommended to use the `--path` flag when installing gems so that they are installed to a local directory.

An example of this can be found here: https://circleci.com/docs/caching/#full-example-of-saving-and-restoring-cache

You may also want to consider using the Ruby Orb which will do this for you automatically and can handle caching for you: https://circleci.com/developer/orbs/orb/circleci/ruby

I will close this issue out, but feel free to re-open if you have any further concerns!
