### ISSUE TITLE
Node LTS not installed in current version 3.2.2

### ISSUE THREAD

**Issue by rouaneta** [CircleCI-Public/cimg-ruby#131]
Hi,

Current Node LTS is 18.16.0 but installed version in ruby image 3.2.2-node is 18.15.0.

From what I read [here](https://github.com/CircleCI-Public/cimg-ruby/blob/f68835152d62650670a705f6b2d1a312afff5d70/3.2/node/Dockerfile#L7), node LTS is used automatically when building the ruby image.

How do you usually manage this? We wait for the next ruby version or is it possible to rebuild an existing ruby image in order to benefit from the latest versions of the other softwares (node in my case)?

The issue I am facing is that I want to update node in our Ruby app, but I would like the CI to use the same node version as the deployed app, to avoid a possible situation where the tests are green on CircleCI but would break in production because of the node bump.

Thanks :)

**Comment by JalexChen** [comment]
hi @rouaneta 

It is likely that when we built ruby 3.2.2, the lts version of node was 18.15.0.

> How do you usually manage this? We wait for the next ruby version or is it possible to rebuild an existing ruby image in order to benefit from the latest versions of the other softwares (node in my case)?

that's correct. because we want builds to be deterministic, the tag cimg/ruby:3.2.2 tag will typically stay the same unless there are security concerns that require patching or another pressing issue. a node version would not qualify in this case.

you could either:
1) extend the repo and create your own image based off the dockerfile
2) use the [node orb ](https://circleci.com/developer/orbs/orb/circleci/node) to change the version of node to match.

**Comment by rouaneta** [comment]
hi @JalexChen,
thanks for the answer.
